"use client";

import { Link } from "@/lib/nav";
import { LegalLayout, LegalSection } from "@/components/legal-layout";

export function TermsPage() {
  return (
    <LegalLayout
      id="terms"
      kicker="Terms of use"
      title="Using Still."
      lede="By checking the agreement box and making an account, you agree to these terms. If you do not, do not use Still."
    >
      <LegalSection title="1. What Still is">
        <p>
          Still is an AI companion. It listens, can remember what you ask it to keep, and can help you
          think something through. It is software, not a person, and not a professional service.
        </p>
        <p>
          Still is <strong className="font-medium text-fg">not</strong> therapy, counseling, medical care,
          a crisis line, or a substitute for any of those. The Disclaimer says this in more detail and is
          part of these terms.
        </p>
      </LegalSection>

      <LegalSection title="2. Who may use it">
        <p>
          You must be at least 18. Still is not directed at children, and we do not knowingly keep
          accounts for anyone under 18.
        </p>
        <p>
          You must be able to enter a binding agreement in your place. If you use Still on behalf of an
          organization, you confirm you have the right to bind it.
        </p>
      </LegalSection>

      <LegalSection title="3. Your account">
        <p>
          You are responsible for the email and password you choose, and for what happens under that
          account. Keep the password to yourself. Tell the operator if you think the account was used
          without you.
        </p>
        <p>
          You may export or erase the account and companion data kept with the account from You. Erasing
          is permanent and ends the account. You may stop using Still at any time.
        </p>
      </LegalSection>

      <LegalSection title="4. Your words">
        <p>
          You keep whatever rights you have in what you type. You give Still permission to process those
          words so the product can work: to reply, to store memory you allow, to create private
          conversation summaries and weekly reflections, to detect crisis language, and to operate the
          account.
        </p>
        <p>
          Do not use Still to harm someone, to break the law, to try to break the product, or to send
          content you do not have the right to send. We may suspend an account that is used that way.
        </p>
      </LegalSection>

      <LegalSection title="5. How the companion replies">
        <p>
          Replies are generated by a language model (through OpenRouter when a key is configured, or an
          on-device listener if the model cannot be reached). Models can be wrong, incomplete, or unkind
          by accident. Do not rely on Still for medical, legal, or financial decisions.
        </p>
        <p>
          If the words look like a crisis, Still does not invent a free reply. It stays present and
          points to human help. See <Link to="/safety" className="text-fg underline-offset-4 hover:underline">Safety</Link>.
        </p>
      </LegalSection>

      <LegalSection title="6. No professional relationship">
        <p>
          Using Still does not create a therapist–patient, doctor–patient, attorney–client, or any other
          professional relationship. Nothing in the product is advice.
        </p>
      </LegalSection>

      <LegalSection title="7. The service, as it is">
        <p>
          Still is provided “as is” and “as available.” Features change. The model may be unavailable.
          Data may be lost if you only keep a copy in the browser and the browser is cleared, or if a
          database is not configured for the instance you are using.
        </p>
        <p>
          To the fullest extent the law allows, the people who operate this instance are not liable for
          indirect, incidental, special, consequential, or punitive damages, or for lost data, lost
          peace, or decisions you make after talking here. If a court will not allow a full disclaimer,
          liability is limited to the amount you paid to use Still in the last twelve months — which,
          for this product as shipped, is nothing.
        </p>
      </LegalSection>

      <LegalSection title="8. Ending use">
        <p>
          You may leave at any time. We may suspend or end access if these terms are broken, if the
          product is misused, or if the instance is shut down. Survival: sections about your words, the
          disclaimer, limitation of liability, and “as is” remain after the account ends.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes">
        <p>
          These terms can change. The date at the top will move. Continuing to use Still after a change
          means you accept the new terms. If you do not, export what you need and stop.
        </p>
      </LegalSection>

      <LegalSection title="10. Law">
        <p>
          If you operate or use this instance from the United States, these terms are governed by the
          laws of the state where the operator lives or is organized, without regard to conflict-of-law
          rules — except that the Illinois note in the Disclaimer always applies to how Still is
          described. If a part of these terms cannot be enforced, the rest still can.
        </p>
        <p>
          Also read{" "}
          <Link to="/privacy" className="text-fg underline-offset-4 hover:underline">
            Privacy
          </Link>
          ,{" "}
          <Link to="/disclaimer" className="text-fg underline-offset-4 hover:underline">
            Disclaimer
          </Link>
          , and{" "}
          <Link to="/safety" className="text-fg underline-offset-4 hover:underline">
            Safety
          </Link>
          . They are part of this agreement.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
