/**
 * Hard-coded safety net. This path is never generated by the companion model.
 * Classification can flag risk; this module decides what the user actually sees.
 */

export const CRISIS_COPY = {
  presence:
    "I'm staying right here with you. You don't have to go through this moment alone.",
  body: "If you're in immediate danger, or if part of you is considering hurting yourself, please reach a person who can help right now. I can sit with you — I cannot keep you safe the way a human can.",
  close:
    "I'll still be here if you want to keep talking. This hour is survivable even when it doesn't feel that way.",
} as const;

export interface CrisisResource {
  id: string;
  name: string;
  detail: string;
  href: string;
  action: string;
}

export const CRISIS_RESOURCES: CrisisResource[] = [
  {
    id: "iasp",
    name: "Find a local helpline",
    detail: "International Association for Suicide Prevention — local resources by country.",
    href: "https://www.iasp.info/suicidalthoughts/",
    action: "Open directory",
  },
  {
    id: "988",
    name: "988 Suicide & Crisis Lifeline",
    detail: "United States. Call or text 988 — 24 hours, free, confidential.",
    href: "tel:988",
    action: "Call 988",
  },
  {
    id: "ctl",
    name: "Crisis Text Line",
    detail: "Text HOME to 741741 in the US. Local numbers vary by country.",
    href: "sms:741741?body=HOME",
    action: "Text 741741",
  },
];

const CRISIS_PATTERNS: RegExp[] = [
  /\bkill(?:ing)? myself\b/i,
  /\bend(?:ing)? my life\b/i,
  /\btake my (own )?life\b/i,
  /\bwant to die\b/i,
  /\bwanna die\b/i,
  /\bi (?:don't|do not|dont) want to (?:be alive|live)\b/i,
  /\bbetter off dead\b/i,
  /\bsuicid(?:e|al)\b/i,
  /\bself[-\s]?harm\b/i,
  /\b(?:cut|cutting) myself\b/i,
  /\bhurt myself\b/i,
  /\bno reason to live\b/i,
  /\b(?:can't|cannot|cant) go on\b/i,
  /\bi have a plan\b/i,
  /\boverdos(?:e|ing)\b/i,
  /\bi['’]m done with (?:life|living)\b/i,
  /\b(?:don't|dont|do not) want to wake up\b/i,
  /\bnot worth living\b/i,
  /\bwish i (?:was|were) dead\b/i,
  /\bwish i (?:wasn't|weren't|was not) (?:here|alive)\b/i,
  /\bi['’]m going to kill myself\b/i,
  /\bhang myself\b/i,
  /\bjump off\b/i,
];

const OUTPUT_UNSAFE: RegExp[] = [
  ...CRISIS_PATTERNS,
  /\bhere(?:'s| is) how (?:you|to)\b.*\b(?:die|kill|overdose|hang)\b/i,
  /\byou should (?:kill|hurt) yourself\b/i,
  /\bit(?:'s| is) (?:a good idea|understandable) to (?:end|die|suicide)\b/i,
];

export function detectCrisis(text: string): boolean {
  const t = text.trim();
  if (!t) return false;
  return CRISIS_PATTERNS.some((re) => re.test(t));
}

export function outputLooksUnsafe(text: string): boolean {
  return OUTPUT_UNSAFE.some((re) => re.test(text));
}

export function crisisCompanionText(): string {
  return `${CRISIS_COPY.presence}\n\n${CRISIS_COPY.body}\n\n${CRISIS_COPY.close}`;
}
