/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppCheckInsRouteImport } from './routes/_app/check-ins'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppTalkRouteImport } from './routes/_app/talk'
import { Route as AppYouRouteImport } from './routes/_app/you'
import { Route as ApiCompanionRouteImport } from './routes/api/companion'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCheckInsRoute = AppCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppTalkRoute = AppTalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => AppRoute,
} as any)
const AppYouRoute = AppYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AppRoute,
} as any)
const ApiCompanionRoute = ApiCompanionRouteImport.update({
  id: '/api/companion',
  path: '/api/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-ins': typeof AppCheckInsRoute
  '/memory': typeof AppMemoryRoute
  '/talk': typeof AppTalkRoute
  '/you': typeof AppYouRoute
  '/api/companion': typeof ApiCompanionRoute
  '/api/memory': typeof ApiMemoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-ins': typeof AppCheckInsRoute
  '/memory': typeof AppMemoryRoute
  '/talk': typeof AppTalkRoute
  '/you': typeof AppYouRoute
  '/api/companion': typeof ApiCompanionRoute
  '/api/memory': typeof ApiMemoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/check-ins': typeof AppCheckInsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/talk': typeof AppTalkRoute
  '/_app/you': typeof AppYouRoute
  '/api/companion': typeof ApiCompanionRoute
  '/api/memory': typeof ApiMemoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-ins'
    | '/memory'
    | '/talk'
    | '/you'
    | '/api/companion'
    | '/api/memory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-ins'
    | '/memory'
    | '/talk'
    | '/you'
    | '/api/companion'
    | '/api/memory'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/check-ins'
    | '/_app/memory'
    | '/_app/talk'
    | '/_app/you'
    | '/api/companion'
    | '/api/memory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiCompanionRoute: typeof ApiCompanionRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/check-ins': {
      id: '/_app/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof AppCheckInsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talk': {
      id: '/_app/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof AppTalkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/you': {
      id: '/_app/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof AppYouRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/companion': {
      id: '/api/companion'
      path: '/api/companion'
      fullPath: '/api/companion'
      preLoaderRoute: typeof ApiCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCheckInsRoute: typeof AppCheckInsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppTalkRoute: typeof AppTalkRoute
  AppYouRoute: typeof AppYouRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckInsRoute: AppCheckInsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppTalkRoute: AppTalkRoute,
  AppYouRoute: AppYouRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiCompanionRoute: ApiCompanionRoute,
  ApiMemoryRoute: ApiMemoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
